"""
app/core/cms_defaults.py
------------------------
Default canonical data for the Aarambh Institute public website.
Used for initial database seeding and "Reset to Defaults" in Admin CMS.
"""

from __future__ import annotations

from typing import Any

DEFAULT_SITE_PAGES: dict[str, dict[str, Any]] = {
    "home": {
        "hero_badge": "Admissions Open 2026-27 • Hawa Bangla, Indore",
        "hero_title_prefix": "Excel in Boards with",
        "hero_title_highlight": "Expert Guidance",
        "hero_description": "15 Years of trusted coaching for Class 4th to 12th & Degree Courses (MP Board, CBSE & ICSE). Small batches of 20 students, personalized attention, and proven 98.5% top results.",
        "usp_points": [
            "Strict 20 Students per Batch",
            "Weekly Tests & Instant Doubt Clearing",
            "Expert Faculty (Up to 30 Yrs Experience)",
            "Student-Friendly Affordable Fees (From ₹800/mo)",
        ],
        "primary_cta_text": "Join Free Demo Class",
        "secondary_cta_text": "View Courses",
        "stats": {
            "years_experience": "15+ Yrs",
            "total_students": "2,000+",
            "highest_board_score": "98.5%",
            "board_pass_rate": "98%",
            "faculty_count": "7 Educators",
            "batch_size_limit": "20 Students",
        },
    },
    "about": {
        "title": "Empowering Students With Values, Safety & Excellence",
        "subtitle": "At Aarambh Institute, we believe that the right guidance at the right time transforms a student's academic journey. Located in Hawa Bangla, Indore, we combine veteran teaching legacy with personalized student care.",
        "paragraphs": [
            "Aarambh Institute was founded in 2015 by Mrs. Shobhna Vyas with a clear vision: to establish an academic environment where no student is left behind in overcrowded classrooms.",
            "With over 15 years of institutional presence and veteran educators boasting up to 30 years of teaching mastery, we have guided thousands of students across MP Board, CBSE, and ICSE examinations.",
            "Our hallmark is our strict 20-student batch capacity, dedicated weekly testing system, daily doubt clearing clinics, and transparent, student-friendly fee structures.",
        ],
        "director_name": "Mrs. Shobhna Vyas",
        "director_designation": "Founder & Academic Director",
        "director_experience": "20 Years Teaching Experience",
        "director_quote": "As a parent myself, I know what you want: safety, learning, and happiness for your child. At Aarambh Institute, you will get all three. Let's grow together.",
        "award_title": "Best Coaching Institute Award, Indore 2023",
        "core_values": [
            {"title": "Child Safety First", "desc": "Protected, CCTV-monitored and encouraging learning environment."},
            {"title": "Effective Learning", "desc": "Proven concept-building, model test series, and analytical speed drills."},
            {"title": "Joyful Environment", "desc": "Education with happiness and zero fear, building lifelong confidence."},
        ],
    },
    "courses": {
        "title": "Coaching Classes From Class 4th to 12th & Degree Courses",
        "subtitle": "Covering MP Board, CBSE & ICSE curriculums with experienced faculty, small batches, and student-friendly fees in Indore.",
        "courses_list": [
            {
                "id": "middle-school",
                "category": "school",
                "title": "Class 4th to 8th (Middle School)",
                "subtitle": "All Subjects Comprehensive Coaching for MP Board, CBSE & ICSE",
                "target": "Classes 4th, 5th, 6th, 7th & 8th",
                "duration": "1 Academic Year",
                "board": "MP Board / CBSE / ICSE",
                "timings": "Morning 11:00 AM - 12:30 PM | Evening 5:00 PM - 6:30 PM",
                "batch_size": "Strict 20 Students per batch",
                "fee": "₹800/- to ₹1,000/- (Monthly)",
                "badge": "Junior Foundation",
                "badge_color": "bg-blue-50 text-blue-700 border-blue-200",
                "features": [
                    "All Subjects Covered (Maths, Science, English, Hindi, Social Science)",
                    "Weekly Assessment Tests with Parent Progress Reports",
                    "Printed Comprehensive Study Material & Practice Worksheets",
                    "Daily Dedicated Doubt Clearing & Homework Guidance",
                    "Special focus on Handwriting, Reading & Basic Mathematical Speed",
                ],
                "popular": True,
            },
            {
                "id": "high-school",
                "category": "board",
                "title": "Class 9th to 12th (Board & Entrance)",
                "subtitle": "Science (PCM / PCB) & Commerce Stream Mastery for Board Exams",
                "target": "Classes 9th, 10th, 11th & 12th",
                "duration": "1 Academic Year",
                "board": "MP Board / CBSE / ICSE",
                "timings": "Morning 11:00 AM - 1:00 PM | Evening 4:00 PM - 6:00 PM",
                "batch_size": "Small Batches (20 Students)",
                "fee": "Student-Friendly Affordable Fees",
                "badge": "Board Result Rankers",
                "badge_color": "bg-red-50 text-[#c22329] border-red-200",
                "features": [
                    "All Core Subjects: Physics, Chemistry, Maths, Biology, Commerce & Accounts",
                    "Weekly Topic Tests + Monthly Full Board Model Examination Papers",
                    "Previous 10 Years Board Papers analysis and Answer-Writing Drills",
                    "Special NEET & JEE Mains Foundation Concepts covered by Expert Mentors",
                    "Daily 1:1 Doubt Classes with Senior HODs (15+ to 30 Yrs Experience)",
                ],
                "popular": True,
            },
            {
                "id": "college-degrees",
                "category": "college",
                "title": "College Degrees (B.Com, M.Com, BBA, MBA, B.Sc)",
                "subtitle": "Specialized Higher Education & Commerce/Management Coaching",
                "target": "Undergraduate & Postgraduate Students",
                "duration": "Semester / Academic Year",
                "board": "University Syllabus Aligned",
                "timings": "Flexible Morning & Evening College Batches",
                "batch_size": "Personalized Domain Batches",
                "fee": "Affordable Package Rates",
                "badge": "Higher Education",
                "badge_color": "bg-amber-50 text-amber-800 border-amber-200",
                "features": [
                    "Financial Accounting, Corporate Accounting, Taxation & Costing",
                    "Business Studies, Economics, Statistics & Financial Management",
                    "Taught by Veteran Commerce Head Mr. Jitendra Shindey (30 Yrs Experience)",
                    "University Exam Pattern Model Question Banks & Solved Papers",
                    "Concept clearing for Competitive Exams (Bank PO, CA Foundation, CAT)",
                ],
                "popular": False,
            },
        ],
    },
    "faculty": {
        "title": "Meet Our Veteran Educators",
        "subtitle": "Experienced subject heads with up to 30 years of teaching legacy, dedicated to individual student mentorship.",
        "faculty_list": [
            {
                "name": "Mr. Pankaj Dubey",
                "subject": "Biology",
                "experience": "30 Years Experience",
                "highlight": "Senior Biology Expert • PMT/NEET & Board Specialist",
                "specialty": "Botany, Zoology & Medical Foundation",
                "initials": "PD",
                "avatar_bg": "bg-emerald-50 text-emerald-800",
                "subject_badge": "bg-emerald-50 text-emerald-800 border-emerald-200",
            },
            {
                "name": "Mr. Jitendra Shindey",
                "subject": "Commerce & Accounts",
                "experience": "30 Years Experience",
                "highlight": "Senior Commerce Mentor • 11th-12th, B.Com & M.Com",
                "specialty": "Financial Accounting, Tax & Corporate Laws",
                "initials": "JS",
                "avatar_bg": "bg-blue-50 text-blue-800",
                "subject_badge": "bg-blue-50 text-blue-800 border-blue-200",
            },
            {
                "name": "Mrs. Shobhna Vyas",
                "subject": "Maths & Science (Founder)",
                "experience": "20 Years Experience",
                "highlight": "Founder & Academic Director, Aarambh Institute",
                "specialty": "Conceptual Mathematics & Science for 4th to 10th",
                "initials": "SV",
                "avatar_bg": "bg-red-50 text-[#c22329]",
                "subject_badge": "bg-red-50 text-[#c22329] border-red-200",
            },
            {
                "name": "Mr. Vishal Rathore",
                "subject": "Mathematics",
                "experience": "15 Years Experience",
                "highlight": "Senior Mathematics Specialist for Board Exams",
                "specialty": "Algebra, Calculus & Trigonometry Mastery",
                "initials": "VR",
                "avatar_bg": "bg-amber-50 text-amber-800",
                "subject_badge": "bg-amber-50 text-amber-800 border-amber-200",
            },
            {
                "name": "Mrs. Anita Holkar",
                "subject": "Physics",
                "experience": "15 Years Experience",
                "highlight": "Physics Senior Educator for MP Board & CBSE",
                "specialty": "Mechanics, Electricity, Optics & Numerical Clarity",
                "initials": "AH",
                "avatar_bg": "bg-cyan-50 text-cyan-800",
                "subject_badge": "bg-cyan-50 text-cyan-800 border-cyan-200",
            },
            {
                "name": "Mr. Ansh Sir",
                "subject": "Chemistry, Biology, Physics",
                "experience": "5 Years Experience",
                "highlight": "NEET + JEE Mains Category Specialist",
                "specialty": "Competitive Speed Techniques & Problem Solving",
                "initials": "AS",
                "avatar_bg": "bg-purple-50 text-purple-800",
                "subject_badge": "bg-purple-50 text-purple-800 border-purple-200",
            },
            {
                "name": "Miss Darshna Panchal",
                "subject": "Business Studies & Economics",
                "experience": "2 Years Experience",
                "highlight": "Teaching & Institutional Management Expertise",
                "specialty": "Business Management, Micro & Macro Economics",
                "initials": "DP",
                "avatar_bg": "bg-rose-50 text-rose-800",
                "subject_badge": "bg-rose-50 text-rose-800 border-rose-200",
            },
        ],
    },
    "results": {
        "title": "Celebrating Academic Excellence & Merit Rankers",
        "subtitle": "Consistent 98% board pass results driven by small-batch attention and rigorous practice.",
        "featured_toppers": [
            {
                "name": "Prince",
                "grade": "Class 12th",
                "board": "MP Board",
                "score": "94%",
                "marks": "580 / 600",
                "rank": "Rank 1st",
                "year": "2023",
                "subjects": "Maths: 100/100 • Physics: 99/100",
                "quote": "Aarambh ne mujhe sahi direction diya aur regular practice sets ki wajah se board exam mein top rank mili.",
                "initials": "PR",
                "badge_color": "bg-amber-100 text-amber-900 border-amber-300",
            },
            {
                "name": "Rohit Garg",
                "grade": "Class 10th",
                "board": "MP Board",
                "score": "91%",
                "marks": "Board Distinction",
                "rank": "Rank 2nd",
                "year": "2024",
                "subjects": "Maths & Physics Topper",
                "quote": "Proud to be an Aarambhian! The teachers personally cleared every doubt before the exams.",
                "initials": "RG",
                "badge_color": "bg-blue-100 text-blue-900 border-blue-300",
            },
            {
                "name": "Payal Sharma",
                "grade": "Class 10th",
                "board": "MP Board",
                "score": "89%",
                "marks": "Board Distinction",
                "rank": "Rank 3rd",
                "year": "2024",
                "subjects": "Maths & Chemistry Distinction",
                "quote": "Aarambh didn't just teach me, it transformed me. Concepts were made crystal clear.",
                "initials": "PS",
                "badge_color": "bg-emerald-100 text-emerald-900 border-emerald-300",
            },
        ],
        "all_toppers": [
            {"name": "Prince", "class_name": "12th", "board": "MP Board", "score": "94%", "year": "2023", "highlight": "Rank 1st (Maths 100/100)"},
            {"name": "Rohit Garg", "class_name": "10th", "board": "MP Board", "score": "91%", "year": "2024", "highlight": "Rank 2nd"},
            {"name": "Payal Sharma", "class_name": "10th", "board": "MP Board", "score": "89%", "year": "2024", "highlight": "Rank 3rd"},
            {"name": "Neha Yadav", "class_name": "10th", "board": "MP Board", "score": "89%", "year": "2023", "highlight": "Distinction"},
            {"name": "Nupur", "class_name": "10th", "board": "CBSE", "score": "89%", "year": "2023", "highlight": "Distinction"},
            {"name": "Monika", "class_name": "12th", "board": "CBSE", "score": "85%", "year": "2024", "highlight": "Distinction"},
            {"name": "Ritika Sarothiya", "class_name": "10th", "board": "CBSE", "score": "85%", "year": "2025", "highlight": "Distinction"},
            {"name": "Nishtha Jain", "class_name": "10th", "board": "MP Board", "score": "83%", "year": "2025", "highlight": "First Division"},
            {"name": "Shrishti Yadav", "class_name": "9th", "board": "MP Board", "score": "A Grade", "year": "2025", "highlight": "Class Topper"},
            {"name": "Vanshika Yadav", "class_name": "7th", "board": "MP Board", "score": "A Grade", "year": "2025", "highlight": "Class Topper"},
            {"name": "Atharva Choudhary", "class_name": "8th", "board": "CBSE", "score": "A Grade", "year": "2025", "highlight": "School Star"},
        ],
        "testimonials": [
            {
                "name": "Dhruvika",
                "class_info": "Class 6th",
                "year": "2023",
                "role": "Parent Review",
                "review": "Aarambh Institute ke teachers bahut dedicated hain. Mere bachche ke marks aur confidence dono mein kaafi improvement hua hai. Hum institute ki teaching aur guidance se bahut santusht hain.",
            },
            {
                "name": "Yashika",
                "class_info": "Class 7th",
                "year": "2024",
                "role": "Student Review",
                "review": "Aarambh Institute mein padhai ka environment bahut positive hai. Teachers har topic ko simple aur interesting tareeke se samjhate hain, jis se padhai aasan lagti hai.",
            },
            {
                "name": "Vaishnavi Patel",
                "class_info": "Class 10th (Boards)",
                "year": "2025",
                "role": "Student Review",
                "review": "Regular tests, personal attention aur progress updates ki wajah se humein performance ka poora pata rehta hai. Aarambh Institute sach mein students ke future ko lekar serious hai.",
            },
            {
                "name": "Rishabh Bhargav",
                "class_info": "Class 11th (Science)",
                "year": "2025",
                "role": "Student Review",
                "review": "Yahan mujhe padhai ke saath motivation bhi milta hai. Teachers hamesha support karte hain aur doubts ko turant solve karte hain.",
            },
            {
                "name": "Gourav Sarothiya",
                "class_info": "Class 10th (Boards)",
                "year": "2024",
                "role": "Student Review",
                "review": "Best guidance for academic success! Highly recommended for all board students in Indore.",
            },
        ],
    },
    "admissions": {
        "title": "Join Aarambh Institute With 2 Days Free Trial Class",
        "subtitle": "We welcome students from Class 4th to 12th (MP Board, CBSE, ICSE) and Degree programs. Because we strictly limit each batch to 20 students, seats fill up quickly.",
        "admission_steps": [
            {
                "step": "01",
                "title": "Call or WhatsApp For Enquiry",
                "desc": "Contact our Indore helpline at 88397-14081 or 79097-14081 to know course details, subjects, and batch slots.",
            },
            {
                "step": "02",
                "title": "Visit For A Free Demo Class",
                "desc": "Come to our campus at 8 Shantinath Puri, Hawa Bangla (Near Sai Mandir). Experience our classroom teaching firsthand.",
            },
            {
                "step": "03",
                "title": "Fill Form & Submit Documents",
                "desc": "Complete the simple admission form. Attach: Previous year marksheet, Student Aadhar Card, and 2 passport photos.",
            },
            {
                "step": "04",
                "title": "Pay Fees & Get Batch Timing",
                "desc": "Pay the student-friendly monthly fee and receive your confirmed morning or evening batch schedule.",
            },
        ],
        "documents_required": [
            "Photocopy of previous class marksheet / term report card",
            "Photocopy of Student's Aadhar Card (for identity verification)",
            "2 recent passport-size student photographs",
            "Parent/guardian contact number and WhatsApp information",
        ],
        "fee_highlights": [
            "Classes 4th to 8th: ₹800/- to ₹1,000/- monthly (all subjects included)",
            "Classes 9th to 12th: Affordable subject & combo packages with monthly options",
            "College Degrees: Semester and subject-wise commerce/degree packages",
            "No hidden charges for test series or formula booklets",
        ],
        "faqs": [
            {
                "question": "What is the batch size at Aarambh Institute?",
                "answer": "Unlike crowded coaching classes with 60-100 students, Aarambh Institute maintains a strict cap of only 20 students per batch. This allows teachers to give personalized attention to every student, check daily classwork, and resolve individual doubts.",
            },
            {
                "question": "Who teaches the classes — senior faculty or assistants?",
                "answer": "All classes are taught exclusively by our senior subject educators (having up to 30 years experience), including Mr. Pankaj Dubey (Biology), Mr. Jitendra Shindey (Commerce), and Director Mrs. Shobhna Vyas.",
            },
            {
                "question": "Which boards and classes are taught at the Hawa Bangla campus?",
                "answer": "We coach MP Board (Hindi & English Medium), CBSE, and ICSE curriculums for Class 4th through 12th, plus undergraduate degree programs (B.Com, M.Com, BBA, MBA, B.Sc).",
            },
            {
                "question": "What is the fee structure at Aarambh Institute?",
                "answer": "Our fee structure is transparent and student-friendly. Middle school fees start from ₹800 - ₹1,000/month. High school and degree courses offer affordable monthly and semester packages with scholarship discounts for toppers.",
            },
            {
                "question": "Can I attend a free demo class before taking admission?",
                "answer": "Yes! Every prospective student is entitled to 2 days of free demo trial classes in their relevant batch before deciding on enrollment.",
            },
        ],
    },
    "contact": {
        "institute_name": "Aarambh Institute",
        "tagline": "Step Toward Success • Est. 2015",
        "full_address": "8 Shantinath Puri, Hawa Bangla, Near Sai Mandir, Indore, Madhya Pradesh — 452009",
        "primary_phone": "88397-14081",
        "secondary_phone": "79097-14081",
        "whatsapp_number": "88397-14081",
        "email": "aarambhinstitute09@gmail.com",
        "working_hours": "10:00 AM to 8:00 PM (Monday to Saturday)",
        "google_maps_url": "https://maps.app.goo.gl/T2m2g9b8tjVMCDqL9",
        "footer_tagline": "Education with values. Learning with joy.",
    },
    "student_corner": {
        "title": "Student Resources, Notices & Academic Downloads",
        "subtitle": "Free formula sheets, test schedules, holiday timetables, and campus announcements for Aarambh students.",
        "notices": [
            {
                "date": "24 March 2026",
                "title": "Weekly Board Mock Test Series (Sunday Batch)",
                "desc": "Mandatory for Class 10th and 12th students. Timings: 11:00 AM to 1:00 PM. Answer sheet evaluation will be handed over to parents on Wednesday.",
                "priority": "High Priority",
                "color": "bg-red-50 text-[#c22329] border-red-200",
            },
            {
                "date": "20 March 2026",
                "title": "New Academic Session (2026-27) Admissions Open",
                "desc": "Classes 4th to 12th & Degree programs. Limited 20 seats per batch. Avail early bird fee benefits at Hawa Bangla campus.",
                "priority": "Admission Alert",
                "color": "bg-blue-50 text-blue-700 border-blue-200",
            },
            {
                "date": "15 March 2026",
                "title": "Doubt Clearing Clinic with HODs",
                "desc": "Special extra classes every evening from 6:00 PM to 7:00 PM for physics numericals and organic chemistry reactions.",
                "priority": "Academic",
                "color": "bg-amber-50 text-amber-800 border-amber-200",
            },
        ],
        "holidays": [
            {"holiday": "Mahavir Jayanti", "date": "April 2026", "status": "Holiday"},
            {"holiday": "Good Friday / Ambedkar Jayanti", "date": "April 2026", "status": "Holiday"},
            {"holiday": "Summer Break (Junior Batches Only)", "date": "May 15 - May 25, 2026", "status": "Special Timings"},
            {"holiday": "Independence Day & Raksha Bandhan", "date": "August 2026", "status": "Celebration"},
            {"holiday": "Ganesh Chaturthi / Anant Chaturdashi", "date": "September 2026", "status": "Holiday"},
            {"holiday": "Dussehra & Diwali Break", "date": "October / November 2026", "status": "Festival Break"},
        ],
        "materials": [
            {
                "title": "Class 10th Maths All Formulas Booklet",
                "target_class": "Class 10th (MP Board / CBSE)",
                "pages": "18 Pages",
                "size": "2.4 MB PDF",
                "downloads": "1,240+ Downloads",
                "author": "Mrs. Shobhna Vyas & Mr. Vishal Rathore",
                "badge": "Most Popular",
                "badge_color": "bg-red-50 text-[#c22329] border-red-200",
            },
            {
                "title": "Class 12th Physics Quick Revision & Derivations",
                "target_class": "Class 12th Science",
                "pages": "26 Pages",
                "size": "3.8 MB PDF",
                "downloads": "980+ Downloads",
                "author": "Mrs. Anita Holkar",
                "badge": "Board Special",
                "badge_color": "bg-blue-50 text-blue-700 border-blue-200",
            },
            {
                "title": "Class 12th Biology High-Yield NCERT Diagrams",
                "target_class": "Class 12th Bio / NEET",
                "pages": "22 Pages",
                "size": "4.5 MB PDF",
                "downloads": "1,550+ Downloads",
                "author": "Mr. Pankaj Dubey",
                "badge": "NEET High-Yield",
                "badge_color": "bg-emerald-50 text-emerald-800 border-emerald-200",
            },
        ],
        "scholarship_tests": [
            {"date": "Sunday, 29th March 2026", "time": "10:00 AM - 11:30 AM", "mode": "Online & Offline"},
            {"date": "Sunday, 5th April 2026", "time": "10:00 AM - 11:30 AM", "mode": "Online & Offline"},
            {"date": "Sunday, 12th April 2026", "time": "10:00 AM - 11:30 AM", "mode": "Online & Offline"},
        ],
    },
}
